databases:
  - name: mysite_db
    databaseName: mysite_db
    user: admin
    region: singapore
    plan: free

services:
  - type: web
    name: yudaisugiyama_portfolio
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY 
        value: 4
    autoDeploy: true